apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
  labels:
    app: test
spec:
  containers:
  - name: test
    image: private-registry.registry.svc.cluster.local:30838/generate-addresses
    command: ["sleep", "100000"]
