apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
  labels:
    app: test
spec:
  containers:
  - name: test
    image: private-registry.registry.svc.cluster.local:30838/generate-addresses
    command: ["/bin/sh", "-c"]
    args:
    - /catapult/bin/catapult.tools.address --generate=50 --network=mijin-test > /tmp/raw_addresses_path.txt;
      sleep 100000

